### ISSUE TITLE
Character scan opened the Trailblazer Profile, Phone Wallpaper, Redemption code menu and errored out

### ISSUE THREAD

**Issue by No-Face-the-3rd** [kel-z/HSR-Scanner#102]
When doing a full scan with the 1.2.1-2 release, when it finished the relic section, it went back to the phone pause menu, then the menu I mentioned in the issue title opened and it errored and had the following log

[01:12:40] [INFO] > Quantity: 1979/2000.
[01:22:02] [INFO] > Finished scanning relics.
[01:22:02] [INFO] > Scanning characters...
[01:22:04] [INFO] > Character total: .
[01:22:04] [WARN] > Failed to parse character count. Retrying... (1/5)
[01:22:06] [INFO] > Character total: .
[01:22:06] [WARN] > Failed to parse character count. Retrying... (2/5)
[01:22:07] [INFO] > Character total: .
[01:22:07] [WARN] > Failed to parse character count. Retrying... (3/5)
[01:22:08] [INFO] > Character total: .
[01:22:08] [WARN] > Failed to parse character count. Retrying... (4/5)
[01:22:09] [INFO] > Character total: .
[01:22:09] [WARN] > Failed to parse character count. Retrying... (5/5)
[01:22:11] [INFO] > Character total: .
[01:22:11] [FATAL] > Scan aborted with error ValueError: Failed to parse character count from Data Bank screen.
Stack trace: "Traceback (most recent call last):
  File "services\scanner\scanner.py", line 426, in scan_characters
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 615, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "services\scanner\scanner.py", line 163, in start_scan
  File "services\scanner\scanner.py", line 431, in scan_characters
ValueError: Failed to parse character count from Data Bank screen.
" (Try increasing nav/scan delay in the scanner settings, or scan with a different in-game background, window resolution, or fullscreen/windowed mode.)

**Comment by kel-z** [comment]
Thanks for the report. Does this happen every time you do a character scan? What if you changed the phone menu background?

**Comment by No-Face-the-3rd** [comment]
It happened the two times I attempted last night, but will give another go with a different phone background later today.

**Comment by No-Face-the-3rd** [comment]
Ok, did some further tests, doesn't appear to be due to the phone wallpaper at all, it seems like it's due to, for some reason, after doing the lightcone+relic scan it takes longer to get back to the phone screen than when getting back after doing the lightcone scan alone and so it's just trying to do what it needs to before the game's ready for the input. If I run characters alone, it appears to work fine.

**Comment by No-Face-the-3rd** [comment]
I tried adding 1000 ms to navigation delay and that resolved it, but it's kinda weird that it broke that way when it'd worked fine before. I guess the game might just not run as well on my machine now or something.

**Comment by kel-z** [comment]
Added a retry mechanism for initial character scan phase to hopefully resolve issues related to slow phone menu opening after relic + light cone scan. If this is still not resolved, then maybe need to changing order of scans so that character scan happens first.
