### ISSUE TITLE
Program not clicking on menu options

### ISSUE THREAD

**Issue by Nasz231** [kel-z/HSR-Scanner#72]
Whenever I try to start the program, it gets to my inventory but can't click on anything. The mouse only moves. I tried running as administrator, restarting my laptop, and changing the aspect ratio, but still got the same issue. It doesn't seem to be able to click on anything but move my mouse. This is the error I get: 

[12:29:12] [INFO] > Starting scan...
[12:29:12] [INFO] > Scanning light cones...
[12:29:20] [INFO] > Quantity: .
[12:29:20] [WARN] > Failed to parse quantity. Retrying... (1/5)
[12:29:24] [INFO] > Quantity: .
[12:29:24] [WARN] > Failed to parse quantity. Retrying... (2/5)
[12:29:28] [INFO] > Quantity: .
[12:29:28] [WARN] > Failed to parse quantity. Retrying... (3/5)
[12:29:32] [INFO] > Quantity: .
[12:29:32] [WARN] > Failed to parse quantity. Retrying... (4/5)
[12:29:36] [INFO] > Quantity: .
[12:29:36] [WARN] > Failed to parse quantity. Retrying... (5/5)
[12:29:39] [INFO] > Quantity: .
[12:29:39] [FATAL] > Scan aborted with error ValueError: Failed to parse quantity from inventory screen.
Stack trace: "Traceback (most recent call last):
  File "services\scanner\scanner.py", line 235, in scan_inventory
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 581, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "services\scanner\scanner.py", line 125, in start_scan
  File "services\scanner\scanner.py", line 240, in scan_inventory
ValueError: Failed to parse quantity from inventory screen.
" (Try increasing nav/scan delay in the scanner settings, or scan with a different in-game background, window resolution, or fullscreen/windowed mode.)

**Comment by Nasz231** [comment]
I've tried 1980x1080 (windowed and fullscreen) and 1600x900

**Comment by kel-z** [comment]
Hello! The mouse being able to move but isn't able to click is usually a sign that the app isn't running in administrator mode. When you start the scan, does it ever exit the cellphone menu and open the inventory screen?

**Comment by Nasz231** [comment]
Yes, it does. For some reason, when it opens to my artifact inventory screen (was the last menu I clicked on before I started the program), it thinks it's in the lightcone menu, and the mouse moves as if it is on the lightcone screen. I have a video for more clarity on the issue. I clicked run as administrator on the program and have the resolution as 1600x900 windowed.

**Comment by Nasz231** [comment]
https://youtu.be/rChOsB1PQFw

**Comment by kel-z** [comment]
Right, if the mouse click isn't working then it wouldn't be able to click on the light cone tab icon when it opens the inventory screen. This might be hard to diagnose, I'm unable to find anything related to mouse click problems with pynput (the python library used for keyboard and mouse inputs). Do you think there might be any mouse software that could be interfering with the automated clicks? (also I can't view your youtube video because it's set to private at the moment.)

**Comment by Nasz231** [comment]
So I finally figured it out. Apparently, my mouse default settings switched the primary and secondary buttons. This would explain why I had to click on the right-mouse button instead of the left-one on an actual mouse. Switching this off fixed the issue.

![mouse](https://github.com/kel-z/HSR-Scanner/assets/97503595/13d6aa14-c0a7-4886-9f5c-7fdc3f98084c)
