### ISSUE TITLE
Error I cannot understand

### ISSUE THREAD

**Issue by Bogdan-Stankov** [kel-z/HSR-Scanner#85]
I keep getting the same error, and after reading about and trying the possible mentioned solutions, I am completely lost as to what might cause it. I enabled debug mode and the screenshots seem to be saving ok, but 10-15ish relics into OCR it stops (I am only running it on relics for now). The error is:

[09:42:52] [FATAL] > Scan aborted with error FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<name>\\AppData\\Local\\Temp\\tess_sq3pgc9b.txt'

Sometimes it's another file in the same folder, but it's always FileNotFoundError

**Comment by Bogdan-Stankov** [comment]
I have everything that got saved in the log file

[09:42:52] [FATAL] > Scan aborted with error FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<name>\\AppData\\Local\\Temp\\tess_sq3pgc9b.txt'
Stack trace: "Traceback (most recent call last):
  File "main.py", line 614, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "services\scanner\scanner.py", line 190, in start_scan
  File "asyncio\threads.py", line 25, in to_thread
  File "concurrent\futures\thread.py", line 58, in run
  File "services\scanner\parsers\relic_strategy.py", line 181, in parse
  File "services\scanner\parsers\relic_strategy.py", line 126, in extract_stats_data
  File "utils\ocr.py", line 40, in image_to_string
  File "pytesseract\pytesseract.py", line 423, in image_to_string
  File "pytesseract\pytesseract.py", line 426, in <lambda>
  File "pytesseract\pytesseract.py", line 290, in run_and_get_output
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<nmae>\\AppData\\Local\\Temp\\tess_sq3pgc9b.txt'

**Comment by kel-z** [comment]
Does this still happen? This is a very strange error. Not sure where to begin with this and googling doesn't provide much insight either.

**Comment by Bogdan-Stankov** [comment]
Hey,, I tried testing again and the problem was almost certainly my antivirus. I noticed it say it wants to isolate tesseract.exe this time, and when I told it not to, it ran normally.

**Comment by Bogdan-Stankov** [comment]
Hey,, I tried testing again and the problem was almost certainly my antivirus. I noticed it say it wants to isolate tesseract.exe this time, and when I told it not to, it ran normally.

**Comment by kel-z** [comment]
Ah I see. Thank you for letting me know!
